CREATE TABLE IF NOT EXISTS sensor_data (
    timestamp INTEGER NOT NULL,
    s1 REAL,
    s2 REAL,
    s3 REAL,
    s4 REAL,
    s5 REAL,
    s6 REAL,
    s7 REAL,
    s8 REAL,
    s9 REAL,
    s10 REAL,
    s11 REAL,
    s12 REAL,
    s13 REAL,
    s14 REAL,
    s15 REAL,
    s16 REAL,
    s17 REAL,
    s18 REAL,
    s19 REAL,
    s20 REAL,
    s21 REAL,
    s22 REAL,
    s23 REAL,
    s24 REAL,
    s25 REAL,
    s26 REAL,
    s27 REAL,
    s28 REAL,
    s29 REAL,
    s30 REAL,
    s31 REAL,
    s32 REAL,
    s33 REAL,
    s34 REAL,
    s35 REAL,
    s36 REAL,
    s37 REAL,
    s38 REAL,
    s39 REAL,
    s40 REAL
);

CREATE INDEX IF NOT EXISTS idx_sensor_data_ts ON sensor_data(timestamp);

CREATE TABLE IF NOT EXISTS holding_register (
    timestamp INTEGER NOT NULL,
    h1 INTEGER,
    h2 INTEGER,
    h3 INTEGER,
    h4 INTEGER,
    h5 INTEGER,
    h6 INTEGER,
    h7 INTEGER,
    h8 INTEGER,
    h9 INTEGER,
    h10 INTEGER,
    h11 INTEGER,
    h12 INTEGER,
    h13 INTEGER,
    h14 INTEGER,
    h15 INTEGER,
    h16 INTEGER,
    h17 INTEGER,
    h18 INTEGER,
    h19 INTEGER,
    h20 INTEGER,
    h21 INTEGER,
    h22 INTEGER,
    h23 INTEGER,
    h24 INTEGER,
    h25 INTEGER,
    h26 INTEGER,
    h27 INTEGER,
    h28 INTEGER,
    h29 INTEGER,
    h30 INTEGER,
    h31 INTEGER,
    h32 INTEGER,
    h33 INTEGER,
    h34 INTEGER,
    h35 INTEGER,
    h36 INTEGER,
    h37 INTEGER,
    h38 INTEGER,
    h39 INTEGER,
    h40 INTEGER,
    h41 INTEGER,
    h42 INTEGER,
    h43 INTEGER,
    h44 INTEGER,
    h45 INTEGER,
    h46 INTEGER,
    h47 INTEGER,
    h48 INTEGER,
    h49 INTEGER,
    h50 INTEGER,
    h51 INTEGER,
    h52 INTEGER,
    h53 INTEGER,
    h54 INTEGER,
    h55 INTEGER,
    h56 INTEGER,
    h57 INTEGER,
    h58 INTEGER,
    h59 INTEGER,
    h60 INTEGER,
    h61 INTEGER,
    h62 INTEGER,
    h63 INTEGER,
    h64 INTEGER,
    h65 INTEGER,
    h66 INTEGER,
    h67 INTEGER,
    h68 INTEGER,
    h69 INTEGER,
    h70 INTEGER,
    h71 INTEGER,
    h72 INTEGER,
    h73 INTEGER,
    h74 INTEGER,
    h75 INTEGER,
    h76 INTEGER,
    h77 INTEGER,
    h78 INTEGER,
    h79 INTEGER,
    h80 INTEGER,
    h81 INTEGER,
    h82 INTEGER,
    h83 INTEGER,
    h84 INTEGER,
    h85 INTEGER,
    h86 INTEGER,
    h87 INTEGER,
    h88 INTEGER,
    h89 INTEGER,
    h90 INTEGER,
    h91 INTEGER,
    h92 INTEGER,
    h93 INTEGER,
    h94 INTEGER,
    h95 INTEGER,
    h96 INTEGER,
    h97 INTEGER,
    h98 INTEGER,
    h99 INTEGER,
    h100 INTEGER
);

CREATE INDEX IF NOT EXISTS idx_holding_register_ts ON holding_register(timestamp);

CREATE TABLE IF NOT EXISTS alarm_history (
    id INTEGER PRIMARY KEY,
    occurrence_time INTEGER,
    reason VARCHAR(255)
);

CREATE INDEX IF NOT EXISTS idx_alarm_history_time ON alarm_history(occurrence_time);
